"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR.parent / 'data' / 'web'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.getenv('DEBUG', '0')))

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'django_filters',
    'accounts',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'device',
    'datalogsensor',
]

UNFOLD = {
    "SITE_TITLE": "Painel de Sensores",
    "SITE_HEADER": "Painel de Sensores",
    "SITE_URL": "/",
    "SITE_SYMBOL": "sensors",
    "SITE_FAVICONS": [
        {"rel": "icon", "type": "image/svg+xml", "href": "/static/favicon.svg"},
        {"rel": "alternate icon", "type": "image/png", "href": "/static/favicon.png"},
    ],
    "STYLES": ["/static/admin_custom.css"],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_FULL_RESULT_COUNT": True,
    "DASHBOARD_CALLBACK": "project.admin_dashboard.dashboard_callback",
    "COLORS": {
        "primary": {
            "50":  "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56  189 248",
            "500": "14  165 233",
            "600": "2   132 199",
            "700": "3   105 161",
            "800": "7   89  133",
            "900": "12  74  110",
            "950": "8   47  73",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Monitoramento",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Voltar ao Dashboard",
                        "icon": "arrow_back",
                        "link": "/",
                    },
                ],
            },
            {
                "title": "Dispositivos",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Tipos de Sensor",
                        "icon": "category",
                        "link": "/admin/device/tipo/",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": "Sensores",
                        "icon": "sensors",
                        "link": "/admin/device/sensor/",
                    },
                ],
            },
            {
                "title": "Registros",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Leituras dos Sensores",
                        "icon": "data_table",
                        "link": "/admin/datalogsensor/registro/",
                    },
                ],
            },
            {
                "title": "Usuários e Perfis",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Usuários",
                        "icon": "person",
                        "link": "/admin/auth/user/",
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Perfis",
                        "icon": "manage_accounts",
                        "link": "/admin/accounts/profile/",
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Grupos",
                        "icon": "group",
                        "link": "/admin/auth/group/",
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.perfil',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Banco: PostgreSQL gerenciado do Render, via DATABASE_URL.
# (Sem Postgres no docker-compose — defina DATABASE_URL no .env para rodar local.)
import dj_database_url  # noqa: E402

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# Traduções pt-BR do projeto (inclui textos do Unfold que não vêm traduzidos).
LOCALE_PATHS = [BASE_DIR / 'locale']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
# /data/web/static
STATIC_ROOT = DATA_DIR / 'static'

# Estáticos do projeto (favicon, etc.)
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise serve os estáticos comprimidos em produção.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

MEDIA_URL = '/media/'
# /data/web/media
MEDIA_ROOT = DATA_DIR / 'media'

# Autenticação do dashboard web (login único, sem segunda senha)
# ---- Autenticação (Django + allauth/Google) ----
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'dashboard'
ACCOUNT_LOGOUT_REDIRECT_URL = 'account_login'

# Login por usuário OU e-mail; sem verificação por e-mail (não há SMTP configurado).
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGOUT_ON_GET = True

# Google: clicar no botão já redireciona; casar login social a conta existente pelo e-mail.
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
# Bloqueia criação de novas contas via Google (só o admin cadastra usuários).
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.SocialAdapter'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_OAUTH_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_OAUTH_SECRET', ''),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

# ---- Produção / Render ----
# O Render termina o TLS no proxy e encaminha via http; isto faz o Django (e o
# allauth) reconhecerem a requisição como https (callback do Google correto).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# O Render injeta automaticamente RENDER_EXTERNAL_HOSTNAME (ex: app.onrender.com).
RENDER_HOST = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_HOST:
    if RENDER_HOST not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(RENDER_HOST)
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_HOST}')
