# Generated by Django 4.2.30 on 2026-05-27 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Tipo do sensor')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=30, verbose_name='Nome do Lisímetro')),
                ('local', models.CharField(max_length=30, verbose_name='Local de Instalação')),
                ('macaddress', models.CharField(max_length=11, unique=True, verbose_name='Endereço MAC')),
                ('longitude', models.CharField(max_length=11, null=True, unique=True, verbose_name='Longitude')),
                ('latitude', models.CharField(max_length=11, null=True, unique=True, verbose_name='Latidude')),
                ('observacao', models.TextField(max_length=100, null=True, verbose_name='Observação')),
                ('data_cadastro', models.DateField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.tipo')),
            ],
            options={
                'ordering': ['data_cadastro'],
            },
        ),
    ]
