# Generated by Django 4.2.30 on 2026-05-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor',
            field=models.CharField(max_length=30, verbose_name='Nome do Sensor'),
        ),
    ]
