# Generated by Django 4.2.30 on 2026-05-27 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=10, null=True, verbose_name='Data')),
                ('hora', models.CharField(blank=True, max_length=8, null=True, verbose_name='Hora')),
                ('Massa_Balanca1', models.CharField(blank=True, max_length=8, null=True, verbose_name='Massa da Balança 01')),
                ('Massa_Balanca2', models.CharField(blank=True, max_length=8, null=True, verbose_name='Massa da Balança 02')),
                ('Media_Balancas', models.CharField(blank=True, max_length=8, null=True, verbose_name='Média das Balanças')),
                ('Delta_Massa_Balanca1', models.CharField(blank=True, max_length=8, null=True, verbose_name='Delta da Balança 01')),
                ('Delta_Massa_Balanca2', models.CharField(blank=True, max_length=8, null=True, verbose_name='Delta da Balança 02')),
                ('Delta_Media_Balancas', models.CharField(blank=True, max_length=8, null=True, verbose_name='Delta da Média das Balanças')),
                ('data_registro', models.DateTimeField(auto_now=True, verbose_name='Data do registro')),
                ('Sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.sensor', verbose_name='Identificação do Lisímetro')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
