# Generated by Django 4.2.30 on 2026-05-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalogsensor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='Delta_Massa_Balanca1',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='Delta_Massa_Balanca2',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='Delta_Media_Balancas',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='Massa_Balanca1',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='Massa_Balanca2',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='Media_Balancas',
        ),
        migrations.AddField(
            model_name='registro',
            name='altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Altitude'),
        ),
        migrations.AddField(
            model_name='registro',
            name='pressao',
            field=models.FloatField(blank=True, null=True, verbose_name='Pressão'),
        ),
        migrations.AddField(
            model_name='registro',
            name='temperatura',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura'),
        ),
        migrations.AddField(
            model_name='registro',
            name='umidade',
            field=models.FloatField(blank=True, null=True, verbose_name='Umidade'),
        ),
    ]
