# Generated by Django 4.2.30 on 2026-05-27 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_sensor_sensor'),
        ('datalogsensor', '0002_remove_registro_delta_massa_balanca1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.sensor', verbose_name='Identificação do Sensor'),
        ),
    ]
