# Generated by Django 4.2.30 on 2026-05-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tema',
            field=models.CharField(choices=[('dark', 'Escuro'), ('light', 'Claro')], default='dark', max_length=5, verbose_name='Tema'),
        ),
    ]
